[package]
name = "toy-search-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
# Dependencies for testing
assert_cmd = "2"
assert_fs = "1"
predicates = "2"
